# Generated by Django 5.0.3 on 2024-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_advertisement_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='count_bathrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='count_bedrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
