# Generated by Django 5.0.3 on 2024-05-01 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('paymentTime', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('floor', models.IntegerField()),
                ('typeOfHouse', models.CharField(max_length=255)),
                ('max_people_count', models.IntegerField()),
                ('current_people_count', models.IntegerField()),
                ('count_bedrooms', models.IntegerField()),
                ('count_bathrooms', models.IntegerField()),
                ('numberOfRooms', models.IntegerField()),
                ('square', models.IntegerField()),
                ('isSold', models.BooleanField(default=False)),
                ('isArchived', models.BooleanField(default=False)),
                ('haveWifi', models.BooleanField(default=False)),
                ('haveTV', models.BooleanField(default=False)),
                ('haveWashingMachine', models.BooleanField(default=False)),
                ('haveParking', models.BooleanField(default=False)),
                ('haveConditioner', models.BooleanField(default=False)),
                ('nearbyTradeCenter', models.BooleanField(default=False)),
                ('nearbyHospital', models.BooleanField(default=False)),
                ('nearbySchool', models.BooleanField(default=False)),
                ('nearbyGym', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='relocation/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('relocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.relocation')),
            ],
            options={
                'verbose_name': 'Relocation image',
                'verbose_name_plural': 'Relocation images',
                'db_table': 'relocation_image',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
