# Generated by Django 5.0.3 on 2024-03-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='imagePaths',
            field=models.JSONField(null=True),
        ),
    ]
