# Generated by Django 5.0.3 on 2024-03-30 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_userinfo_address_userinfo_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='backIDCard',
            field=models.ImageField(blank=True, null=True, upload_to='user/id_card/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='frontIDCard',
            field=models.ImageField(blank=True, null=True, upload_to='user/id_card/'),
        ),
        migrations.CreateModel(
            name='AdditionalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('who_is', models.CharField(max_length=100, null=True)),
                ('contacts', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AdditionalUser',
                'verbose_name_plural': 'AdditionalUsers',
                'db_table': 'additional_user',
            },
        ),
    ]
